### ISSUE TITLE
General Roadmap

### ISSUE THREAD

**Issue by jamesturk** [jamesturk/beakers#7]
Using this as a meta-issue to track overall direction.

For 0.1, what is needed is a proof of concept pulling key features from old pipeline, saucebrush, and related projects.  This is mostly there, but a parallel runner is the cherry on top / proof of concept. 

- [x] #2
- [x] README

The work after that is going to be adding niceties, both on the CLI and in usage.  This probably accounts for 0.2 and 0.3, with focus tentatively on UI and developer experience.

- [x] #3 
- [x] #11 
- [x] #4 
- [x] #6 
- [x] #12
- [ ] #9 
- [ ] #5 

Down the line:
- [ ] spatula integration and examples
- [ ] optional web UI
- [ ] pluggable stuff (storage backends, run strategies, etc.)
